INSERT INTO Publishers (name, city) VALUES
('Publisher1', 'Rzeszow'),
('Publisher2', 'Krasne'),
('Publisher3', 'Wroclaw'),
('Publisher4', 'Warszawa');

INSERT INTO Authors (first_name, last_name, date_of_birth, primary_genre, portrait) VALUES
('John Ronald Reuel', 'Tolkien', ('1892-01-03'), 0, FILE_READ('classpath:/static/img/LoadDatabase/JRRTolkien.jpg')),
('Tappei', 'Nagatsuki', ('1987-03-11'), 0, FILE_READ('classpath:/static/img/LoadDatabase/TappeiNagatsuki.jpg')),
('Wojciech', 'Drewniak', ('1977-10-26'), 7, FILE_READ('classpath:/static/img/LoadDatabase/WojciechDrewniak.jpg'));

INSERT INTO Books (title, sub_title, description, publishing_year, cover, author_id, publisher_id) VALUES
('The Fellowship of the Ring', 'The Lord of the Rings Part One', 'The Lord of the Rings. Sauron, the Dark Lord, has gathered to him all the Rings of Power the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring the ring that rules them all which has fallen into the hands of the hobbit, Bilbo Baggins.In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.'
, 1954, FILE_READ('classpath:/static/img/LoadDatabase/TheFellowshipOfTheRing.jpg'), (SELECT id from Authors Where Authors.last_name = 'Tolkien'), (SELECT id from Publishers WHERE Publishers.name = 'Publisher1')),
('The Two Towers', 'The Lord of the Rings Part Two', 'Frodo and the Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in the battle with an evil spirit in the Mines of Moria; and at the Falls of Rauros, Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape the rest of the company were attacked by Orcs. Now they continue their journey alone down the great River Anduin -- alone, that is, save for the mysterious creeping figure that follows wherever they go.'
, 1954, FILE_READ('classpath:/static/img/LoadDatabase/TheTwoTowers.jpg'), (SELECT id from Authors Where Authors.last_name = 'Tolkien'), (SELECT id from Publishers WHERE Publishers.name = 'Publisher1')),
('The Return of the King', 'The Lord of the Rings Part Three', 'While the evil might of the Dark Lord Sauron swarms out to conquer all Middle-earth, Frodo and Sam struggle deep into Mordor, seat of Saurons power. To defeat the Dark Lord, the One Ring, ruler of all the accursed Rings of Power, must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. Weighed down by the compulsion of the Ring, he begins finally to despair.'
, 1955, FILE_READ('classpath:/static/img/LoadDatabase/TheReturnOfTheKing.jpg'), (SELECT id from Authors Where Authors.last_name = 'Tolkien'), (SELECT id from Publishers WHERE Publishers.name = 'Publisher1')),
('Re:zero Starting Life In Another World Vol. 1', '', 'Subaru Natsuki was just trying to get to the convenience store but wound up summoned to another world. He encounters the usual things--life-threatening situations, silver haired beauties, cat fairies--you know, normal stuff. All that would be bad enough, but hes also gained the most inconvenient magical ability of all--time travel, but hes got to die to use it. How do you repay someone who saved your life when all you can do is die?'
, 2014, FILE_READ('classpath:/static/img/LoadDatabase/ReZeroVol1.jpg'), (SELECT id from Authors Where Authors.last_name = 'Nagatsuki'), (SELECT id from Publishers WHERE Publishers.name = 'Publisher2')),
('Historia Bez Cenzury', '', 'Ostrzezenie! Ksiazka zawiera tresci nieodpowiednie dla dzieci oraz kontrowersyjne skroty myslowe. Jesli jest to dla Ciebie powazny problem, zrezygnuj z czytania... chociaz pewnie bedziesz zalowac. Po co ta ksiazka, skoro wszystko jest w internetowym programie? Tak sie sklada, ze nie wszystko. Nie da sie w pietnastominutowym odcinku opowiedziec o jakims wladcy od poczatku do konca. Wiele ciekawych i waznych rzeczy musimy sobie darowac. W tej ksiazce dostajecie >>Historie Bez Cenzury<< w wersji full wypas. Nie bylo zadnych ograniczen dlugosci tekstu. Moglem pisac do momentu, az poczulem: Ok, Wojtas, to chyba wszystko.'
, 2016, FILE_READ('classpath:/static/img/LoadDatabase/HistoriaBezCenzury1.jpg'), (SELECT id from Authors Where Authors.last_name = 'Drewniak'), (SELECT id from Publishers WHERE Publishers.name = 'Publisher3')),
('Historia bez cenzury 3', 'Poland first to fight... czyli II wojna swiatowa' ,'Do trzech razy sztuka! Byli polscy wladcy, byly wielkie koksy... Nadszedl czas na trzecia czesc serii! Oto przed wami II Wojna Swiatowa bez cenzury! Zaloz mundur, zgarnij karabin pod pache i wyrusz w podroz po najslynniejszych frontach II wojny swiatowej. Poznaj tajemnice, o ktorych nie dowiesz sie z lekcji w szkole. Odkryj kulisy rozszyfrowania enigmy, unies sie w przestworza podczas bitwy o Anglie i dowiedz sie, czemu zawsze to my Polacy bylismy "First to fight" chociaz nikt sie z nami nie cackal.'
, 2018, FILE_READ('classpath:/static/img/LoadDatabase/HistoriaBezCenzury3.jpeg'), (SELECT id from Authors Where Authors.last_name = 'Drewniak'), (SELECT id from Publishers WHERE Publishers.name = 'Publisher4'));

INSERT INTO Users (username, password, matching_password) Values
('Username1', '$2y$12$l2nskAJIGk.5STUwEZ2rBe8lka2debyMExu8j8s8pGfR0gRnOSSPm', '$2y$12$l2nskAJIGk.5STUwEZ2rBe8lka2debyMExu8j8s8pGfR0gRnOSSPm');